version: '3.8'

services:
  shadownode:
    image: ghcr.io/shadownode/shadownode:latest
    restart: always
    networks:
      - shadownode0
    ports:
      - "8080:8080"
      - "2022:2022"
    tty: true
    environment:
      TZ: "UTC"
      SHADOWNODE_UID: 988
      SHADOWNODE_GID: 988
      SHADOWNODE_USERNAME: shadownode
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/"
      - "/etc/shadownode/:/etc/shadownode/"
      - "/var/lib/shadownode/:/var/lib/shadownode/"
      - "/var/log/shadownode/:/var/log/shadownode/"
      - "/tmp/shadownode/:/tmp/shadownode/"
      - "/etc/ssl/certs:/etc/ssl/certs:ro"

networks:
  shadownode0:
    name: shadownode0
    driver: bridge
    ipam:
      config:
        - subnet: "172.21.0.0/16"
    driver_opts:
      com.docker.network.bridge.name: shadownode0
